// Shared types for the Application Cockpit.

export interface JobInput {
  title: string;
  company: string;
  description: string;
  /** Optional application screening questions, one per line (free text). */
  screeningQuestions?: string;
}

export interface ScreeningAnswer {
  question: string;
  answer: string;
}

/** The three deliverables generated per job. */
export interface Materials {
  coverLetter: string;
  videoScript: string;
  screeningAnswers: ScreeningAnswer[];
}

/** A saved job + its generated materials (persisted client-side in localStorage). */
export interface JobRecord extends JobInput {
  id: string;
  materials: Materials;
  createdAt: string;
  /** "mock" when generated without an API key, "live" when generated by Claude. */
  source: "mock" | "live";
}
